# Required Environment Variables (For Upload):
# DOCKER_USER - The username for logging into the Docker registry
# DOCKER_PASSWORD - The password for logging into the Docker registry

# Optional Environment Variables
# DOCKER_REGISTRY - The registry the images will be pushed to, must end with '/'
# CORE_NAME - The main name of the image, to override the original name.

stages:
  - Build Images
  - Upload Images

variables:
  DOCKER_REGISTRY: ''
  CORE_NAME: 'stabletec/build-core'

#############################
# Image Build/Testing Stage #
#############################

.build_image: &build_template
  stage: Build Images
  except:
    - master
  script:
    - ./linux-build.sh

Fedora Build:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
  variables:
    PLATFORMS: "linux/amd64,linux/arm64"
    OS: fedora
  <<: *build_template

CentOS Build:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
  variables:
    PLATFORMS: "linux/amd64,linux/arm64"
    OS: centos
  <<: *build_template

Debian Build:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
    - armv7
  variables:
    PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
    OS: debian
  <<: *build_template

Ubuntu Build:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
    - armv7
  variables:
    PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
    OS: ubuntu
  <<: *build_template

openSUSE Build:
  tags:
    - docker-builder-linux
    - amd64
  variables:
    PLATFORMS: "linux/amd64"
    OS: opensuse
  <<: *build_template

Windows Build:
  stage: Build Images
  except:
    refs:
      - master
    variables:
      - $NO_CACHE
  tags:
    - docker-builder-windows
    - amd64
  script:
    - cd windows; .\image_builder.ps1 -imagename test -test

Windows Build(no cache):
  stage: Build Images
  except:
    refs:
      - master
  only:
    variables:
      - $NO_CACHE  
  tags:
    - docker-builder-windows
    - amd64
  script:
    - cd windows; .\image_builder.ps1 -imagename test -test -n

#######################
# Image Uploads Stage #
#######################

.upload_image: &upload_template
  stage: Upload Images
  only:
    - master
  before_script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
  script:
    - ./linux-upload.sh
  after_script:
    - docker logout ${DOCKER_REGISTRY}

Fedora Upload:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
  variables:
    PLATFORMS: "linux/amd64,linux/arm64"
    OS: fedora
  <<: *upload_template

CentOS Upload:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
  variables:
    PLATFORMS: "linux/amd64,linux/arm64"
    OS: centos
  <<: *upload_template

Debian Upload:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
    - armv7
  variables:
    PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
    OS: debian
  <<: *upload_template

Ubuntu Upload:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
    - armv7
  variables:
    PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
    OS: ubuntu
  <<: *upload_template

openSUSE Upload:
  tags:
    - docker-builder-linux
    - amd64
  variables:
    PLATFORMS: "linux/amd64"
    OS: opensuse
  <<: *upload_template

Windows Upload:
  stage: Upload Images
  only:
    refs:
      - master
  except:
    variables:
      - $NO_CACHE
  tags:
    - docker-builder-windows
    - amd64
  before_script:
    - docker login -u $env:DOCKER_USER -p "$env:DOCKER_PASSWORD" $env:DOCKER_REGISTRY
  script:
    - cd windows; .\image_builder.ps1 -push -imagename ${env:DOCKER_REGISTRY}${env:CORE_NAME} -test
  after_script:
    - docker logout $env:DOCKER_REGISTRY

Windows Upload(no cache):
  stage: Upload Images
  only:
    refs:
      - master
    variables:
      - $NO_CACHE
  tags:
    - docker-builder-windows
    - amd64
  before_script:
    - docker login -u $env:DOCKER_USER -p "$env:DOCKER_PASSWORD" $env:DOCKER_REGISTRY
  script:
    - cd windows; .\image_builder.ps1 -push -imagename ${env:DOCKER_REGISTRY}${env:CORE_NAME} -test -n
  after_script:
    - docker logout $env:DOCKER_REGISTRY