# Optional Environment Variables
# IMAGE_NAME - The main name of the image, to override the original name.

stages:
  - Build Images
  - Upload Images

variables:
  IMAGE_NAME: "stabletec/build-core"

#############################
# Image Build/Testing Stage #
#############################

.linux_build_template: &linux_build_template
  stage: Build Images
  tags:
    - container-builder
    - linux
    - podman
    - qemu
  except:
    - main
  script:
    - ./build-linux.sh $NO_CACHE --image-dir ${IMAGE_DIR} --tag build-core-test --rm

Alma Build:
  variables:
    IMAGE_DIR: alma
  <<: *linux_build_template

Arch/SteamOS Build:
  variables:
    IMAGE_DIR: arch
  <<: *linux_build_template

Fedora Build:
  variables:
    IMAGE_DIR: fedora
  <<: *linux_build_template

Rocky Build:
  variables:
    IMAGE_DIR: rocky
  <<: *linux_build_template

Debian Build:
  variables:
    IMAGE_DIR: debian
  <<: *linux_build_template

Ubuntu Build:
  variables:
    IMAGE_DIR: ubuntu
  <<: *linux_build_template

openSUSE Build:
  variables:
    IMAGE_DIR: opensuse
  <<: *linux_build_template

Windows Build:
  stage: Build Images
  except:
    refs:
      - main
    variables:
      - $NO_CACHE
  tags:
    - container-builder
    - windows
    - amd64
  variables:
    OS: windows
  script:
    - ./build-windows.ps1 -ImageName build-core-test -Test

Windows Build(no cache):
  stage: Build Images
  except:
    refs:
      - main
  only:
    variables:
      - $NO_CACHE
  tags:
    - container-builder
    - windows
    - amd64
  variables:
    OS: windows
  script:
    - ./build-windows.ps1 -ImageName build-core-test -Test -NoCache

#######################
# Image Uploads Stage #
#######################

.linux_upload_template: &linux_upload_template
  stage: Upload Images
  tags:
    - container-builder
    - linux
    - podman
    - qemu
  only:
    - main
  script:
    - ./build-linux.sh $NO_CACHE --image-dir ${IMAGE_DIR} --tag ${IMAGE_NAME} --push

Alma Upload:
  variables:
    IMAGE_DIR: alma
  <<: *linux_upload_template

Arch/SteamOS Upload:
  variables:
    IMAGE_DIR: arch
  <<: *linux_upload_template

Fedora Upload:
  variables:
    IMAGE_DIR: fedora
  <<: *linux_upload_template

Rocky Upload:
  variables:
    IMAGE_DIR: rocky
  <<: *linux_upload_template

Debian Upload:
  variables:
    IMAGE_DIR: debian
  <<: *linux_upload_template

Ubuntu Upload:
  variables:
    IMAGE_DIR: ubuntu
  <<: *linux_upload_template

openSUSE Upload:
  variables:
    IMAGE_DIR: opensuse
  <<: *linux_upload_template

Windows Upload:
  stage: Upload Images
  only:
    refs:
      - main
  except:
    variables:
      - $NO_CACHE
  tags:
    - container-builder
    - windows
    - amd64
  variables:
    OS: windows
  retry: 2
  script:
    - ./build-windows.ps1 -ImageName ${env:IMAGE_NAME} -Test -Push

Windows Upload(no cache):
  stage: Upload Images
  only:
    refs:
      - main
    variables:
      - $NO_CACHE
  tags:
    - container-builder
    - windows
    - amd64
  variables:
    OS: windows
  retry: 2
  script:
    - ./build-windows.ps1 -ImageName ${env:IMAGE_NAME} -Test -Push -NoCache
