image: docker:dind

Build Images (Linux):
  except:
  - master
  tags:
  - linux
  - docker-builder
  script:
  - docker build -t build-core/fedora:gcc-$CI_COMMIT_SHA -f fedora/gcc.dockerfile fedora
  - docker build -t build-core/fedora:clang-$CI_COMMIT_SHA -f fedora/clang.dockerfile fedora
  - docker build -t build-core/centos:gcc-$CI_COMMIT_SHA -f centos/gcc.dockerfile centos
  - docker build -t build-core/centos:clang-$CI_COMMIT_SHA -f centos/clang.dockerfile centos

Build Images (Windows):
  except:
  - master
  tags:
  - windows
  - docker-builder
  script:
  - docker build -t build-core/windows:msvc2017-%CI_COMMIT_SHA% -m 2GB -f windows/msvc2017.dockerfile windows

Build and Push Images (Linux):
  only:
  - master
  tags:
  - linux
  - docker-builder
  script:
    # Build Images
  - docker build -t build-core/fedora:gcc-$CI_COMMIT_SHA -f fedora/gcc.dockerfile fedora
  - docker build -t build-core/fedora:clang-$CI_COMMIT_SHA -f fedora/clang.dockerfile fedora
  - docker build -t build-core/centos:gcc-$CI_COMMIT_SHA -f centos/gcc.dockerfile centos
  - docker build -t build-core/centos:clang-$CI_COMMIT_SHA -f centos/clang.dockerfile centos
    # Tag images
  - docker tag build-core/fedora:gcc-$CI_COMMIT_SHA registry.stabletec.com/docker/build-core/fedora:gcc
  - docker tag build-core/fedora:clang-$CI_COMMIT_SHA registry.stabletec.com/docker/build-core/fedora:clang
  - docker tag build-core/centos:gcc-$CI_COMMIT_SHA registry.stabletec.com/docker/build-core/centos:gcc
  - docker tag build-core/centos:clang-$CI_COMMIT_SHA registry.stabletec.com/docker/build-core/centos:clang
    # Push Images
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.stabletec.com
  - docker push registry.stabletec.com/docker/build-core/fedora:gcc
  - docker push registry.stabletec.com/docker/build-core/fedora:clang
  - docker push registry.stabletec.com/docker/build-core/centos:gcc
  - docker push registry.stabletec.com/docker/build-core/centos:clang

Build and Push Images (Windows):
  only:
  - master
  tags:
  - windows
  - docker-builder
  script:
    # Build Images
  - docker build -t build-core/windows:msvc2017-%CI_COMMIT_SHA% -m 2GB -f windows/msvc2017.dockerfile windows
    # Tag Images
  - docker tag build-core/windows:msvc2017-%CI_COMMIT_SHA% registry.stabletec.com/docker/build-core/windows:msvc2017
    # Push Images
  - docker login -u gitlab-ci-token -p %CI_BUILD_TOKEN% registry.stabletec.com
  - docker push registry.stabletec.com/docker/build-core/windows:msvc2017