# Optional Environment Variables
# IMAGE_NAME - The main name of the image, to override the original name.

stages:
  - Build Images
  - Upload Images

variables:
  IMAGE_NAME: "stabletec/build-core"

#############################
# Image Build/Testing Stage #
#############################

.linux_build_template: &linux_build_template
  stage: Build Images
  tags:
    - container-builder
    - linux
    - podman
    - qemu
  except:
    refs:
      - main
  script:
    - ./build-linux.sh $NO_CACHE --image-dir ${IMAGE_DIR} --tag build-core-test --rm

.windows_build_template: &windows_build_template
  stage: Build Images
  tags:
    - container-builder
    - windows
    - amd64
    - ${WINDOWS_CONTAINER_BASE_VERSION}
  except:
    refs:
      - main
  script:
    - if (!$env:NO_CACHE) { ./build-windows.ps1 -ImageName build-core-test -ImageDir $env:IMAGE_DIR -Test }
    - if ($env:NO_CACHE) { ./build-windows.ps1 -NoCache -ImageName build-core-test -ImageDir $env:IMAGE_DIR -Test }

Alma Build:
  variables:
    IMAGE_DIR: alma
  <<: *linux_build_template

Arch/SteamOS Build:
  variables:
    IMAGE_DIR: arch
  <<: *linux_build_template

Fedora Build:
  variables:
    IMAGE_DIR: fedora
  <<: *linux_build_template

Rocky Build:
  variables:
    IMAGE_DIR: rocky
  <<: *linux_build_template

Debian Build:
  variables:
    IMAGE_DIR: debian
  <<: *linux_build_template

Ubuntu Build:
  variables:
    IMAGE_DIR: ubuntu
  <<: *linux_build_template

openSUSE Build:
  variables:
    IMAGE_DIR: opensuse
  <<: *linux_build_template

Windows Build (2019):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2019
    IMAGE_DIR: windows-ltsc2019
  <<: *windows_build_template

Windows Build (2022):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2022
    IMAGE_DIR: windows-ltsc2022
  <<: *windows_build_template

Windows Build (2025):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2025
    IMAGE_DIR: windows-ltsc2025
  <<: *windows_build_template

MSYS Build (2019):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2019
    IMAGE_DIR: msys-ltsc2019
  <<: *windows_build_template

MSYS Build (2022):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2022
    IMAGE_DIR: msys-ltsc2022
  <<: *windows_build_template

MSYS Build (2025):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2025
    IMAGE_DIR: msys-ltsc2025
  <<: *windows_build_template

#######################
# Image Uploads Stage #
#######################

.linux_upload_template: &linux_upload_template
  stage: Upload Images
  tags:
    - container-builder
    - linux
    - podman
    - qemu
  only:
    refs:
      - main
  script:
    - ./build-linux.sh $NO_CACHE --image-dir ${IMAGE_DIR} --tag ${IMAGE_NAME} --push

.windows_upload_template: &windows_upload_template
  stage: Upload Images
  tags:
    - container-builder
    - windows
    - amd64
    - ${WINDOWS_CONTAINER_BASE_VERSION}
  only:
    refs:
      - main
  script:
    - if (!$env:NO_CACHE) { ./build-windows.ps1 -ImageDir $env:IMAGE_DIR -ImageName $env:IMAGE_NAME -Test -Push }
    - if ($env:NO_CACHE) { ./build-windows.ps1 -NoCache -ImageDir $env:IMAGE_DIR -ImageName $env:IMAGE_NAME -Test -Push }

Alma Upload:
  variables:
    IMAGE_DIR: alma
  <<: *linux_upload_template

Arch/SteamOS Upload:
  variables:
    IMAGE_DIR: arch
  <<: *linux_upload_template

Fedora Upload:
  variables:
    IMAGE_DIR: fedora
  <<: *linux_upload_template

Rocky Upload:
  variables:
    IMAGE_DIR: rocky
  <<: *linux_upload_template

Debian Upload:
  variables:
    IMAGE_DIR: debian
  <<: *linux_upload_template

Ubuntu Upload:
  variables:
    IMAGE_DIR: ubuntu
  <<: *linux_upload_template

openSUSE Upload:
  variables:
    IMAGE_DIR: opensuse
  <<: *linux_upload_template

Windows Upload (2019):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2019
    IMAGE_DIR: windows-ltsc2019
  <<: *windows_upload_template

Windows Upload (2022):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2022
    IMAGE_DIR: windows-ltsc2022
  <<: *windows_upload_template

Windows Upload (2025):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2025
    IMAGE_DIR: windows-ltsc2025
  <<: *windows_upload_template

MSYS Upload (2019):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2019
    IMAGE_DIR: msys-ltsc2019
  <<: *windows_upload_template

MSYS Upload (2022):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2022
    IMAGE_DIR: msys-ltsc2022
  <<: *windows_upload_template

MSYS Upload (2025):
  variables:
    WINDOWS_CONTAINER_BASE_VERSION: ltsc2025
    IMAGE_DIR: msys-ltsc2025
  <<: *windows_upload_template
