# Required Environment Variables (For Upload):
# DOCKER_USER - The username for logging into the Docker registry
# DOCKER_PASSWORD - The password for logging into the Docker registry

# Optional Environment Variables
# DOCKER_REGISTRY - The registry the images will be pushed to, must end with '/'
# CORE_NAME - The main name of the image, to override the original name.

stages:
  - Build Images
  - Upload Images

variables:
  DOCKER_REGISTRY: ''
  CORE_NAME: 'stabletec/build-core'

#############################
# Image Build/Testing Stage #
#############################

.build_image: &build_template
  stage: Build Images
  except:
    - main
  script:
    - ./linux-build.sh --tag test

Arch/SteamOS Build:
  tags:
    - docker-builder-linux
    - amd64
  variables:
    OS: arch
  <<: *build_template

Fedora Build:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
  variables:
    OS: fedora
  <<: *build_template

CentOS Build:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
  variables:
    OS: centos
  <<: *build_template

Debian Build:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
  variables:
    OS: debian
  <<: *build_template

Ubuntu Build:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
    - armv7
    - riscv64
  variables:
    OS: ubuntu
  <<: *build_template

openSUSE Build:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
    - armv7
  variables:
    OS: opensuse
  <<: *build_template

Windows Build:
  stage: Build Images
  except:
    refs:
      - main
    variables:
      - $NO_CACHE
  tags:
    - docker-builder-windows
    - amd64
  script:
    - cd windows; .\image_builder.ps1 -imagename test -test

Windows Build(no cache):
  stage: Build Images
  except:
    refs:
      - main
  only:
    variables:
      - $NO_CACHE  
  tags:
    - docker-builder-windows
    - amd64
  script:
    - cd windows; .\image_builder.ps1 -imagename test -test -n

#######################
# Image Uploads Stage #
#######################

.upload_image: &upload_template
  stage: Upload Images
  only:
    - main
  script:
    - ./linux-build.sh --tag ${DOCKER_REGISTRY}${CORE_NAME} --push
  after_script:
    - docker logout ${DOCKER_REGISTRY}

Arch/SteamOS Upload:
  tags:
    - docker-builder-linux
    - amd64
  variables:
    OS: arch
  <<: *upload_template

Fedora Upload:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
  variables:
    OS: fedora
  <<: *upload_template

CentOS Upload:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
  variables:
    OS: centos
  <<: *upload_template

Debian Upload:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
  variables:
    OS: debian
  <<: *upload_template

Ubuntu Upload:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
    - armv7
    - riscv64
  variables:
    OS: ubuntu
  <<: *upload_template

openSUSE Upload:
  tags:
    - docker-builder-linux
    - amd64
    - arm64
    - armv7
  variables:
    PLATFORMS: "linux/amd64"
    OS: opensuse
  <<: *upload_template

Windows Upload:
  stage: Upload Images
  only:
    refs:
      - main
  except:
    variables:
      - $NO_CACHE
  tags:
    - docker-builder-windows
    - amd64
  before_script:
    - docker login -u $env:DOCKER_USER -p "$env:DOCKER_PASSWORD" $env:DOCKER_REGISTRY
  script:
    - cd windows; .\image_builder.ps1 -push -imagename ${env:DOCKER_REGISTRY}${env:CORE_NAME} -test
  after_script:
    - docker logout $env:DOCKER_REGISTRY

Windows Upload(no cache):
  stage: Upload Images
  only:
    refs:
      - main
    variables:
      - $NO_CACHE
  tags:
    - docker-builder-windows
    - amd64
  before_script:
    - docker login -u $env:DOCKER_USER -p "$env:DOCKER_PASSWORD" $env:DOCKER_REGISTRY
  script:
    - cd windows; .\image_builder.ps1 -push -imagename ${env:DOCKER_REGISTRY}${env:CORE_NAME} -test -n
  after_script:
    - docker logout $env:DOCKER_REGISTRY