# Required Environment Variables (For Upload):
# DOCKER_USER - The username for logging into the Docker registry
# DOCKER_PASSWORD - The password for logging into the Docker registry

##########
# Global #
##########

stages:
  - Build Release Images
  - Build Tagged Images
  - Upload Release Images
  - Upload Tagged Images
  - Post-Pipeline

variables:
  REGISTRY_ADDRESS: ''
  CORE_NAME: 'stabletec/build-core'
  FIRST_SEPARATOR: ':'
  SECOND_SEPARATOR: '-'
  TAG_NAME: ${REGISTRY_ADDRESS}${CORE_NAME}${FIRST_SEPARATOR}${OS}${RELEASE}${SECOND_SEPARATOR}

######################
# Image Builds Stage #
######################

.build_image: &build_template
  image: docker:dind
  tags:
    - linux
    - docker-builder
  script:
    - ./image_builder.sh -b -o ${OS} -r ${RELEASE} -t ${REGISTRY_ADDRESS}${CORE_NAME} -f ${FIRST_SEPARATOR} -s ${SECOND_SEPARATOR} -p -${CI_COMMIT_REF_NAME} ${EXTRA_OPTIONS}

Fedora Latest Build:
  stage: Build Tagged Images
  variables:
    OS: fedora
    RELEASE: 'latest'
  <<: *build_template

CentOS Latest Build:
  stage: Build Tagged Images
  variables:
    OS: centos
    RELEASE: latest
  <<: *build_template

Debian Latest Build:
  stage: Build Tagged Images
  variables:
    OS: debian
    RELEASE: latest
  <<: *build_template

Ubuntu Latest Build:
  stage: Build Tagged Images
  variables:
    OS: ubuntu
    RELEASE: latest
  <<: *build_template

.Windows Build:
  stage: Release Images
  variables:
    OS: windows
    RELEASE: latest
  tags:
    - windows
    - docker-builder
  script:
    - docker build -t %TAG_NAME%msvc2017-%CI_COMMIT_REF_NAME% -m 2GB -f windows/msvc2017.dockerfile windows

#######################
# Image Uploads Stage #
#######################

.upload_image: &upload_template
  image: docker:dind
  only:
    - master
  tags:
    - linux
    - docker-builder
  before_script:
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
    - ./image_builder.sh -bu -o ${OS} -r ${RELEASE} -t ${REGISTRY_ADDRESS}${CORE_NAME} -f ${FIRST_SEPARATOR} -s ${SECOND_SEPARATOR} ${EXTRA_OPTIONS}
  after_script:
    - docker logout ${DOCKER_REGISTRY}

Fedora Latest Upload:
  stage: Upload Tagged Images
  variables:
    OS: fedora
    RELEASE: latest
  <<: *upload_template

CentOS Latest Upload:
  stage: Upload Tagged Images
  variables:
    OS: centos
    RELEASE: latest
  <<: *upload_template

Debian Latest Upload:
  stage: Upload Tagged Images
  variables:
    OS: debian
    RELEASE: latest
  <<: *upload_template

Ubuntu Latest Upload:
  stage: Upload Tagged Images
  variables:
    OS: ubuntu
    RELEASE: latest
  <<: *upload_template

.Windows Upload:
  stage: Release Images
  variables:
    OS: windows
    RELEASE: latest
  only:
    - master
  tags:
    - windows
    - docker-builder
  before_script:
    - docker login -u %DOCKER_USER% -p "%DOCKER_PASSWORD%" %DOCKER_REGISTRY%
  script:
    - docker build -t %TAG_NAME%msvc2017 -m 2GB -f windows/msvc2017.dockerfile windows
    - docker push %TAG_NAME%msvc2017
  after_script:
    - docker logout %DOCKER_REGISTRY%