# Required Environment Variables (For Upload):
# DOCKER_USER - The username for logging into the Docker registry
# DOCKER_PASSWORD - The password for logging into the Docker registry

# Optional Environment Variables
# DOCKER_REGISTRY - The registry the images will be pushed to, must end with '/'
# CORE_NAME - The main name of the image, to override the original name.

##########
# Global #
##########

stages:
  - Build Images
  - Upload Images

variables:
  DOCKER_REGISTRY: ''
  CORE_NAME: 'stabletec/build-core'

######################
# Image Builds Stage #
######################

.build_image: &build_template
  image: docker:dind
  except:
    - master
  tags:
    - docker-linux
  script:
    - ./image_builder.sh -b -t -o ${OS} -i test ${EXTRA_OPTIONS} ${NO_CACHE}

Fedora Build:
  stage: Build Images
  variables:
    OS: fedora
  <<: *build_template

CentOS Build:
  stage: Build Images
  variables:
    OS: centos
  <<: *build_template

Debian Build:
  stage: Build Images
  variables:
    OS: debian
  <<: *build_template

Ubuntu Build:
  stage: Build Images
  variables:
    OS: ubuntu
  <<: *build_template

openSUSE Build:
  stage: Build Images
  variables:
    OS: opensuse
  <<: *build_template

Windows MSVC/ClangCL/Clang Build:
  stage: Build Images
  except:
    refs:
      - master
    variables:
      - $NO_CACHE
  tags:
    - docker-windows
  script:
    - cd windows; .\image_builder.ps1 -imagename test -test

Windows MSVC/ClangCL/Clang Build (no cache):
  stage: Build Images
  except:
    refs:
      - master
  only:
    variables:
      - $NO_CACHE  
  tags:
    - docker-windows
  script:
    - cd windows; .\image_builder.ps1 -imagename test -test -n

#######################
# Image Uploads Stage #
#######################

.upload_image: &upload_template
  image: docker:dind
  only:
    - master
  tags:
    - docker-linux
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
    - ./image_builder.sh -b -t -p -o ${OS} -i ${DOCKER_REGISTRY}${CORE_NAME} ${EXTRA_OPTIONS} ${NO_CACHE}
  after_script:
    - docker logout ${DOCKER_REGISTRY}

Fedora Upload:
  stage: Upload Images
  variables:
    OS: fedora
  <<: *upload_template

CentOS Upload:
  stage: Upload Images
  variables:
    OS: centos
  <<: *upload_template

Debian Upload:
  stage: Upload Images
  variables:
    OS: debian
  <<: *upload_template

Ubuntu Upload:
  stage: Upload Images
  variables:
    OS: ubuntu
  <<: *upload_template

openSUSE Upload:
  stage: Upload Images
  variables:
    OS: opensuse
  <<: *upload_template

Windows MSVC/ClangCL/Clang Upload:
  stage: Upload Images
  only:
    refs:
      - master
  except:
    variables:
      - $NO_CACHE
  tags:
    - docker-windows
  script:
    - docker login -u $env:DOCKER_USER -p "$env:DOCKER_PASSWORD" $env:DOCKER_REGISTRY
    - cd windows; .\image_builder.ps1 -imagename ${env:DOCKER_REGISTRY}${env:CORE_NAME} -test -push
  after_script:
    - docker logout $env:DOCKER_REGISTRY

Windows MSVC/ClangCL/Clang Upload (no cache):
  stage: Upload Images
  only:
    refs:
      - master
    variables:
      - $NO_CACHE
  tags:
    - docker-windows
  script:
    - docker login -u $env:DOCKER_USER -p "$env:DOCKER_PASSWORD" $env:DOCKER_REGISTRY
    - cd windows; .\image_builder.ps1 -imagename ${env:DOCKER_REGISTRY}${env:CORE_NAME} -test -push -n
  after_script:
    - docker logout $env:DOCKER_REGISTRY
