# Required Environment Variables (For Upload):
# DOCKER_USER - The username for logging into the Docker registry
# DOCKER_PASSWORD - The password for logging into the Docker registry

# Optional Environment Variables
# DOCKER_REGISTRY - The registry the images will be pushed to, must end with '/'
# CORE_NAME - The main name of the image, to override the original name.

##########
# Global #
##########

stages:
  - Build Images
  - Upload Images

variables:
  DOCKER_REGISTRY: ''
  CORE_NAME: 'stabletec/build-core'

######################
# Image Builds Stage #
######################

.build_image: &build_template
  image: docker:dind
  except:
    - master
  tags:
    - docker-linux
  script:
    - ./image_builder.sh -b -t -o ${OS} -i test ${EXTRA_OPTIONS} ${NO_CACHE}

Fedora Build:
  stage: Build Images
  variables:
    OS: fedora
  <<: *build_template

CentOS Build:
  stage: Build Images
  variables:
    OS: centos
  <<: *build_template

Debian Build:
  stage: Build Images
  variables:
    OS: debian
  <<: *build_template

Ubuntu Build:
  stage: Build Images
  variables:
    OS: ubuntu
  <<: *build_template

openSUSE Build:
  stage: Build Images
  variables:
    OS: opensuse
  <<: *build_template

Windows Build:
  stage: Build Images
  variables:
    OS: windows
  except:
    - master
  tags:
    - docker-windows
  script:
    - cd windows/msvc2017
    - docker build -t test:windows-msvc2017 -m 4GB .

#######################
# Image Uploads Stage #
#######################

.upload_image: &upload_template
  image: docker:dind
  only:
    - master
  tags:
    - docker-linux
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
    - ./image_builder.sh -b -t -p -o ${OS} -i ${DOCKER_REGISTRY}${CORE_NAME} ${EXTRA_OPTIONS} ${NO_CACHE}
  after_script:
    - docker logout ${DOCKER_REGISTRY}

Fedora Upload:
  stage: Upload Images
  variables:
    OS: fedora
  <<: *upload_template

CentOS Upload:
  stage: Upload Images
  variables:
    OS: centos
  <<: *upload_template

Debian Upload:
  stage: Upload Images
  variables:
    OS: debian
  <<: *upload_template

Ubuntu Upload:
  stage: Upload Images
  variables:
    OS: ubuntu
  <<: *upload_template

openSUSE Upload:
  stage: Upload Images
  variables:
    OS: opensuse
  <<: *upload_template

Windows Upload:
  stage: Upload Images
  variables:
    OS: windows
  only:
    - master
  tags:
    - docker-windows
  before_script:
    - docker login -u %DOCKER_USER% -p "%DOCKER_PASSWORD%" %DOCKER_REGISTRY%
  script:
    - cd windows/msvc2017
    - docker build %NO_CACHE% -t %DOCKER_REGISTRY%%CORE_NAME%:windows-msvc2017 -m 4GB .
    - docker push %DOCKER_REGISTRY%%CORE_NAME%:windows-msvc2017
  after_script:
    - docker logout %DOCKER_REGISTRY%