# Optional Environment Variables
# IMAGE_NAME - The main name of the image, to override the original name.

stages:
  - Build Images
  - Upload Images

variables:
  IMAGE_NAME: 'stabletec/build-core'

#############################
# Image Build/Testing Stage #
#############################

.build_image: &build_template
  stage: Build Images
  tags:
    - container-builder
    - linux
    - podman
    - qemu
  except:
    - main
  script:
    - ./linux-build.sh $NO_CACHE --tag test --rm

Alma Build:
  variables:
    OS: alma
  <<: *build_template

Arch/SteamOS Build:
  variables:
    OS: arch
  <<: *build_template

Fedora Build:
  variables:
    OS: fedora
  <<: *build_template

CentOS Build:
  variables:
    OS: centos
  <<: *build_template

Rocky Build:
  variables:
    OS: rocky
  <<: *build_template

Debian Build:
  variables:
    OS: debian
  <<: *build_template

Ubuntu Build:
  variables:
    OS: ubuntu
  <<: *build_template

openSUSE Build:
  variables:
    OS: opensuse
  <<: *build_template

Windows Build:
  stage: Build Images
  except:
    refs:
      - main
    variables:
      - $NO_CACHE
  tags:
    - docker-builder-windows
    - amd64
  script:
    - cd windows; .\image_builder.ps1 -ImageName test -Test

Windows Build(no cache):
  stage: Build Images
  except:
    refs:
      - main
  only:
    variables:
      - $NO_CACHE  
  tags:
    - docker-builder-windows
    - amd64
  script:
    - cd windows; .\image_builder.ps1 -ImageName test -Test -NoCache

#######################
# Image Uploads Stage #
#######################

.upload_image: &upload_template
  stage: Upload Images
  tags:
    - container-builder
    - linux
    - podman
    - qemu
  only:
    - main
  retry: 2
  script:
    - ./linux-build.sh $NO_CACHE --tag ${IMAGE_NAME} --push

Alma Upload:
  variables:
    OS: alma
  <<: *upload_template

Arch/SteamOS Upload:
  variables:
    OS: arch
  <<: *upload_template

Fedora Upload:
  variables:
    OS: fedora
  <<: *upload_template

CentOS Upload:
  variables:
    OS: centos
  <<: *upload_template

Rocky Upload:
  variables:
    OS: rocky
  <<: *upload_template

Debian Upload:
  variables:
    OS: debian
  <<: *upload_template

Ubuntu Upload:
  variables:
    OS: ubuntu
  <<: *upload_template

openSUSE Upload:
  variables:
    OS: opensuse
  <<: *upload_template

Windows Upload:
  stage: Upload Images
  only:
    refs:
      - main
  except:
    variables:
      - $NO_CACHE
  tags:
    - docker-builder-windows
    - amd64
  retry: 2
  script:
    - cd windows; .\image_builder.ps1 -ImageName ${env:IMAGE_NAME} -Test -Push

Windows Upload(no cache):
  stage: Upload Images
  only:
    refs:
      - main
    variables:
      - $NO_CACHE
  tags:
    - docker-builder-windows
    - amd64
  retry: 2
  script:
    - cd windows; .\image_builder.ps1 -ImageName ${env:IMAGE_NAME} -Test -Push -NoCache